- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/part_perms.yml
    - include_tasks: tasks/wazuh_agent.yml
    - include_tasks: tasks/coretto_jdk.yml
    - include_tasks: tasks/grub_cfg.yml
    - include_tasks: tasks/ufw_cfg.yml
    - include_tasks: tasks/journald_cfg.yml
    - include_tasks: tasks/nvm_install.yml
