- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/Frostivious/ansible_pull.git /dev/null"

- name: install cron job (nightly apt update/upgrade with conditional reboot)
  cron:
    user: ansible
    name: "nightly apt upgrade"
    minute: "30"
    hour: "2"
    job: "/usr/bin/apt update && /usr/bin/apt upgrade -y && [ -f /var/run/reboot-required ] && /sbin/reboot >> /var/log/apt-nightly.log 2>&1"

- name: Ensure cron directories are owned by root
  file:
    path: "{{ item }}"
    owner: root
    group: root
    recurse: yes
  loop:
    - /etc/cron.d
    - /etc/cron.daily
    - /etc/cron.hourly
    - /etc/cron.monthly
    - /etc/cron.yearly

- name: Ensure /etc/crontab is owned by root
  file:
    path: /etc/crontab
    owner: root
    group: root

- name: Set restrictive permissions on cron directories
  file:
    path: "{{ item }}"
    mode: "0750"
    recurse: yes
  loop:
    - /etc/cron.d
    - /etc/cron.daily
    - /etc/cron.hourly
    - /etc/cron.monthly
    - /etc/cron.yearly

- name: Set restrictive permissions on /etc/crontab
  file:
    path: /etc/crontab
    mode: "0640"

- name: Set ACLs on cron directories for ansible and serelna
  acl:
    path: "{{ item[1] }}"
    entity: "{{ item[0] }}"
    etype: user
    permissions: rx
    state: present
    recursive: yes
  with_nested:
    - [ 'ansible', 'serelna' ]
    -
      - /etc/cron.d
      - /etc/cron.daily
      - /etc/cron.hourly
      - /etc/cron.monthly
      - /etc/cron.yearly

- name: Set ACLs on /etc/crontab for ansible and serelna
  acl:
    path: /etc/crontab
    entity: "{{ item }}"
    etype: user
    permissions: r
    state: present
  loop:
    - ansible
    - serelna
