- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/Frostivious/ansible_pull.git /dev/null"

- name: install cron job (nightly apt update/upgrade with conditional reboot)
  cron:
    user: ansible
    name: "nightly apt upgrade"
    minute: "30"
    hour: "2"
    job: "/usr/bin/apt update && /usr/bin/apt upgrade -y && [ -f /var/run/reboot-required ] && /sbin/reboot >> /var/log/apt-nightly.log 2>&1"

- name: Ensure permissions on /etc/crontab are configured - CIS 5.1.2
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: '0600'
- name: Ensure permissions on /etc/cron.hourly are configured - CIS 5.1.3
  ansible.builtin.file:
    path: /etc/cron.hourly
    owner: root
    group: root
    mode: '0600'
- name: Ensure permissions on /etc/cron.daily are configured - CIS 5.1.4
  ansible.builtin.file:
    path: /etc/cron.daily
    owner: root
    group: root
    mode: '0600'
- name: Ensure permissions on /etc/cron.weekly are configured - CIS 5.1.5
  ansible.builtin.file:
    path: /etc/cron.weekly
    owner: root
    group: root
    mode: '0600'
- name: Ensure permissions on /etc/cron.monthly are configured - CIS 5.1.6
  ansible.builtin.file:
    path: /etc/cron.monthly
    owner: root
    group: root
    mode: '0600'
- name: Ensure permissions on /etc/cron.d are configured - CIS 5.1.7
  ansible.builtin.file:
    path: /etc/cron.d
    owner: root
    group: root
    mode: '0600'
