- name: Syncs nftables conf with github
  ansible.builtin.get_url:
    url: https://github.com/Frostivious/ansible_pull/blob/main/files/nftbales.conf
    dest: /etc/nftables.conf
  register: nftmp

- name: Restart nftables
  shell: systemctl restart nftables
  when: nftmp.changed
