- name: Adds Cramfs to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^cramfs'
    line: install cramfs /bin/false
    state: present

- name: Adds freevxfs to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^freevxfs'
    line: install freevxfs /bin/false
    state: present

- name: Adds hfs to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^hfs'
    line: install hfs /bin/false
    state: present

- name: Adds hfsplus to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^hfsplus'
    line: install hfsplus /bin/false
    state: present

- name: Adds jffs2 to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^jffs2'
    line: install jffs2 /bin/false
    state: present

- name: Adds overlayfs to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^overlayfs'
    line: install overlayfs /bin/false
    state: present

- name: Adds squashfs to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^squashfs'
    line: install squashfs /bin/false
    state: present

- name: Adds udf to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^udf'
    line: install udf /bin/false
    state: present

- name: Adds usb-storage to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^usb-storage'
    line: install usb-storage /bin/false
    state: present

- name: Adds dccp to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^dccp'
    line: install dccp /bin/false
    state: present

- name: Adds tipc to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^tipc'
    line: install tipc /bin/false
    state: present

- name: Adds rds to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^rds'
    line: install rds /bin/false
    state: present

- name: Adds sctp to Blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: '^sctp'
    line: install sctp /bin/false
    state: present
