- name: Install Packages
  apt:
    name:
      - htop
      - gnupg
      - apt-transport-https
      - python3-pip
      - auditd
      - audispd-plugins
      - acl
      - apparmor-utils
      - ufw
      - libpam-pwquality
      - systemd-journal-remote

- name: Remove Packages
  apt:
    name:
      - telnet
      - ntp
      - telnetd
      - inetutils-telnet
      - telnetd-ssl
      - gdm3
      - nftables
      - rsync
      - gdm3

    state: absent

- name: Removed unused dependencies
  apt:
    autoremove: true
