- name: Install Packages
  apt:
    name:
      - htop
      - gnupg
      - apt-transport-https
      - python3-pip
      - auditd
      - audispd-plugins
      - acl
      - apparmor-utils
      - nftables

- name: Remove Packages
  apt:
    name:
      - telnet
      - ntp
      - telnetd
      - inetutils-telnet
      - telnetd-ssl
      - gdm3
      - iptables
      - ufw
      - iptables-persistent

    state: absent
- name: Removed unused dependencies
  apt:
    autoremove: true
