- name: Ensure mount points have required mount options
  become: yes
  block:
    - name: Ensure /tmp is mounted with noexec, nodev, and nosuid
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/vda7\s+/tmp\s+'
        line: '/dev/vda7 /tmp ext4 defaults,noexec,nodev,nosuid 0 2'
        backup: yes
      register: tmp_fstab_change
    - name: Remount /tmp if required
      ansible.builtin.command: mount -o remount,noexec,nodev,nosuid /tmp
      when: tmp_fstab_change.changed
      changed_when: false

    - name: Ensure /var is mounted with nodev and nosuid
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/vda3\s+/var\s+'
        line: '/dev/vda3 /var ext4 defaults,nodev,nosuid 0 2'
        backup: yes
      register: var_fstab_change
    - name: Remount /var if required
      ansible.builtin.command: mount -o remount,nodev,nosuid /var
      when: var_fstab_change.changed
      changed_when: false

    - name: Ensure /var/tmp is mounted with noexec, nodev, and nosuid
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/vda6\s+/var/tmp\s+'
        line: '/dev/vda6 /var/tmp ext4 defaults,noexec,nodev,nosuid 0 2'
        backup: yes
      register: var_tmp_fstab_change
    - name: Remount /var/tmp if required
      ansible.builtin.command: mount -o remount,noexec,nodev,nosuid /var/tmp
      when: var_tmp_fstab_change.changed
      changed_when: false

    - name: Ensure /var/log is mounted with noexec, nodev, and nosuid
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/vda4\s+/var/log\s+'
        line: '/dev/vda4 /var/log ext4 defaults,noexec,nodev,nosuid 0 2'
        backup: yes
      register: var_log_fstab_change
    - name: Remount /var/log if required
      ansible.builtin.command: mount -o remount,noexec,nodev,nosuid /var/log
      when: var_log_fstab_change.changed
      changed_when: false

    - name: Ensure /var/log/audit is mounted with noexec, nodev, and nosuid
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/vda5\s+/var/log/audit\s+'
        line: '/dev/vda5 /var/log/audit ext4 defaults,noexec,nodev,nosuid 0 2'
        backup: yes
      register: var_log_audit_fstab_change
    - name: Remount /var/log/audit if required
      ansible.builtin.command: mount -o remount,noexec,nodev,nosuid /var/log/audit
      when: var_log_audit_fstab_change.changed
      changed_when: false

    - name: Ensure /home is mounted with nodev and nosuid
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/vda6\s+/home\s+'
        line: '/dev/vda6 /home ext4 defaults,nodev,nosuid 0 2'
        backup: yes
      register: home_fstab_change
    - name: Remount /home if required
      ansible.builtin.command: mount -o remount,nodev,nosuid /home
      when: home_fstab_change.changed
      changed_when: false
