- name: Sets nodev, no suid, noexec for /tmp
  mount: >
    name="/tmp"
    src={{ item.device }}
    state=mounted
    fstype= {{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/tmp"
  with_items: ansible_mounts

- name: Sets nodev, no suid, for /var
  mount: >
    name="/var"
    src={{ item.device }}
    state=mounted
    fstype= {{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/var"
  with_items: ansible_mounts

- name: Sets nodev, no suid, noexec for /var/tmp
  mount: >
    name="/var/tmp"
    src={{ item.device }}
    state=mounted
    fstype= {{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/var/tmp"
  with_items: ansible_mounts

- name: Sets nodev, no suid, noexec for /var/log
  mount: >
    name="/var/log"
    src={{ item.device }}
    state=mounted
    fstype= {{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/var/log"
  with_items: ansible_mounts

- name: Sets nodev, no suid, noexec for /var/log/audit
  mount: >
    name="/var/log/audit"
    src={{ item.device }}
    state=mounted
    fstype= {{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/var/log/audit"
  with_items: ansible_mounts

- name: Sets nodev, no suid, for /home
  mount: >
    name="/home"
    src={{ item.device }}
    state=mounted
    fstype= {{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/home"
  with_items: ansible_mounts
