- name: Ensure Different Partitions are restricted
  mount:
    name: /tmp
    src: none
    fstype: tmpfs
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    name: /var
    src: none
    fstype: tmpfs
    state: mounted
    opts: nodev,nosuid

  mount:
    name: /var/tmp
    src: none
    fstype: tmpfs
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    name: /var/log
    src: none
    fstype: tmpfs
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    name: /var/log/audit
    src: none
    fstype: tmpfs
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    name: /home
    src: none
    fstype: tmpfs
    state: mounted
    opts: nodev,nosuid
