- name: Ensure Different Partitions are restricted
  mount:
    path: /tmp
    src: /dev/vda7
    fstype: ext4
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    path: /var
    src: /dev/vda3
    fstype: ext4
    state: mounted
    opts: nodev,nosuid

  mount:
    path: /var/tmp
    src: /dev/vda6
    fstype: ext4
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    path: /var/log
    src: /dev/vda4
    fstype: ext4
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    path: /var/log/audit
    src: /dev/vda5
    fstype: ext4
    state: mounted
    opts: noexec,nodev,nosuid

  mount:
    path: /home
    src: /dev/vda8
    fstype: ext4
    state: mounted
    opts: nodev,nosuid
