- name: Ensure /tmp is mounted with noexec
  become: yes
  block:
    - name: Ensure /tmp mount entry in fstab has noexec
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/vda7\s+/tmp\s+'
        line: '/dev/vda7 /tmp ext4 defaults,noexec 0 2'
        backup: yes

    - name: Remount /tmp with noexec
      ansible.builtin.command: mount -o remount,noexec /tmp
      changed_when: false  # Avoid false positives unless you want to track this
