- name: Check current mount options for /tmp
  command: mount | grep 'on /tmp '
  register: tmp_mount

- name: Remount /tmp with secure options if needed
  ansible.posix.mount:
    path: /tmp
    src: /dev/vda7
    fstype: ext4
    opts: noexec,nodev,nosuid
    state: remounted
    fstab: yes
  when: "'noexec' not in tmp_mount.stdout or 'nosuid' not in tmp_mount.stdout or 'nodev' not in tmp_mount.stdout"
