- name: Sets nodev, no suid, noexec for /tmp
  mount: >
    name="/tmp"
    src={{ item.device }}
    state=mounted
    fstype= {{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/tmp"
