- name: Ensure permissions on sshd_config
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0700'

- name: Ensure permissions on sshd_config.d file/s
  file:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    owner: root
    group: root
    mode: '0700'

- name: Adjusts sshd ClientAliveInterval
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveInterval'
    line: ClientAliveInterval 15
    state: present

- name: Adjusts sshd ClientAliveCountMax
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveCountMax'
    line: ClientAliveCountMax 3
    state: present

- name: Disables sshd x11 Forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^DisableForwarding'
    line: DisableForwarding yes
    state: present

- name: Adds a ssh login grace time
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^LoginGraceTime'
    line: LoginGraceTime 45
    state: present

- name: Adjusts max Authorization tries for ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxAuthTries'
    line: MaxAuthTries 4
    state: present

- name: Disables root login over SSH making is so that escalation is required
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: PermitRootLogin no
    state: present

