- name: Enable ufw
  ufw:
    state: enabled

- name: Allow port 22 (SSH)
  command: ufw allow 22

- name: Allow port 80 (HTTP)
  command: ufw allow 80

- name: Allow out port 80 (HTTP)
  command: ufw allow out 80/tcp

- name: Allow port 443 (HTTPS)
  command: ufw allow 443

- name: Allow out port 443 (HTTPS)
  command: ufw allow out 443/tcp

- name: Allow port 53 (DNS)
  command: ufw allow 53

- name: Allow out port 53 (DNS)
  command: ufw allow out 53/udp

- name: Allow port 123 (NTP)
  command: ufw allow 123

- name: Allow out port 123 (NTP)
  command: ufw allow out 123/udp

- name: Allow port 25 (SMTP)
  command: ufw allow 25

- name: Allow port 587 (SMTP Submission)
  command: ufw allow 587

- name: Allow port 3306 (MySQL)
  command: ufw allow 3306

- name: Allow port 5432 (PostgreSQL)
  command: ufw allow 5432

- name: Allow port 9418 (Git)
  command: ufw allow 9418

- name: Allow out port 9418 (Git)
  command: ufw allow out 9418/tcp

- name: Allow SSH to (Git)
  command: ufw allow out to 192.30.252.0/22 port 22

- name: Set default UFW policy to deny incoming traffic
  command: ufw default deny incoming

- name: Set default UFW policy to deny outgoing traffic
  command: ufw default deny outgoing

- name: Allow incoming loopback traffic
  command: ufw allow in on lo

- name: Allow outgoing loopback traffic
  command: ufw allow out on lo

- name: Deny incoming traffic from 127.0.0.0/8
  command: ufw deny in from 127.0.0.0/8

- name: Deny incoming traffic from ::1
  command: ufw deny in from ::1
