- name: Enable ufw
  ufw:
    state: enabled

- name: Allow port 22 (SSH)
  command: ufw allow 22

- name: Allow port 80 (HTTP)
  command: ufw allow 80

- name: Allow out port 80 (HTTP)
  command: ufw allow out 80/tcp

- name: Allow port 443 (HTTPS)
  command: ufw allow 443

- name: Allow out port 443 (HTTPS)
  command: ufw allow out 443/tcp

- name: Allow port 53 (DNS)
  command: ufw allow 53

- name: Allow out port 53 (DNS)
  command: ufw allow out 53/udp

- name: Allow port 123 (NTP)
  command: ufw allow 123

- name: Allow out port 123 (NTP)
  command: ufw allow out 123/udp

- name: Allow port 25 (SMTP)
  command: ufw allow 25

- name: Allow port 587 (SMTP Submission)
  command: ufw allow 587

- name: Allow port 3306 (MySQL)
  command: ufw allow 3306

- name: Allow port 5432 (PostgreSQL)
  command: ufw allow 5432

- name: Allow port 9418 (Git)
  command: ufw allow 9418

- name: Allow out port 9418 (Git)
  command: ufw allow out 9418/tcp

- name: Allow SSH to (Git)
  command: ufw allow out to 192.30.252.0/22 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 185.199.108.0/22 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 140.82.112.0/20 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 143.55.64.0/20 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.201.28.151/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.205.243.166/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.87.245.0/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 4.237.22.38/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.207.73.82/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.27.177.113/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.200.245.247/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.175.192.147/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.233.83.145/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.29.134.23/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.199.39.232/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.217.135.5/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 4.225.11.194/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 4.208.26.197/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.26.156.215/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.201.28.152/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.205.243.160/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.87.245.4/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 4.237.22.40/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.207.73.83/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.27.177.118/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.200.245.248/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.175.192.146/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.233.83.149/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.29.134.19/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.199.39.227/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.217.135.4/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 4.225.11.200/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 4.208.26.198/32 port 22

- name: Allow SSH to (Git)
  command: ufw allow out to 20.26.156.214/32 port 22

- name: Set default UFW policy to deny incoming traffic
  command: ufw default deny incoming

- name: Set default UFW policy to deny outgoing traffic
  command: ufw default deny outgoing

- name: Allow incoming loopback traffic
  command: ufw allow in on lo

- name: Allow outgoing loopback traffic
  command: ufw allow out on lo

- name: Deny incoming traffic from 127.0.0.0/8
  command: ufw deny in from 127.0.0.0/8

- name: Deny incoming traffic from ::1
  command: ufw deny in from ::1
